# Generated by Django 4.2.30 on 2026-08-28 05:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='badge',
            field=models.CharField(blank=True, choices=[('', 'No Badge'), ('new', 'New Arrival'), ('premium', 'Premium'), ('bestseller', 'Bestseller'), ('trending', 'Trending'), ('popular', 'Popular'), ('signature', 'Signature'), ('luxury', 'Luxury'), ('special', 'Special'), ('bridal', 'Bridal'), ('couture', 'Couture')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='design',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='design',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))]),
        ),
        migrations.AddField(
            model_name='design',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
