# Generated by Django 4.2.30 on 2026-08-31 10:22

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_stockitem_stockmovement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'verbose_name': 'Customer Profile', 'verbose_name_plural': 'Customer Profiles'},
        ),
        migrations.AlterModelOptions(
            name='stockitem',
            options={'ordering': ['item_name'], 'verbose_name': 'Stock Item', 'verbose_name_plural': 'Stock Items'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Stock Movement', 'verbose_name_plural': 'Stock Movements'},
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], max_length=5),
        ),
        migrations.AlterField(
            model_name='whychooseus',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
