# Generated by Django 4.2.30 on 2026-09-02 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_aboutsection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockitem',
            options={'ordering': ['id'], 'verbose_name': 'Stock Item', 'verbose_name_plural': 'Stock Items'},
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='sku_code',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='design',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='app.design'),
        ),
    ]
